### ISSUE TITLE
Camera is not stopped when quit

### ISSUE THREAD

**Issue by yubaoliu** [martinruenz/maskfusion#22]
I use 
- kinect v2 
-  ./MaskFusion -v2

I saw this error when quitting my program, and the Kinect camera still running after quitting the program.

Error:
`Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1290, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.5/threading.py", line 1013, in _delete
    del _active[get_ident()]
KeyError: 139809078914176
terminate called without an active exception
Aborted (core dumped)
`
Also, how can I set PYTHON_VE_PATH when I use Anaconda.

Thanks

**Comment by Lick-Lee** [comment]
Hello, Did you solve this problem ? When I ran Maskfusion with two GPU , I met the same problem. I used two GPU(980Ti), one gpu for Mask RCNN, another for SLAM.
There has another problem, When I ran Maskfusion with the .klg log file, it always stopped before the end. It means there have some frames left.
